export type IconNames =
  | "appLogo"
  | "mouseDown"
  | "cross"
  | "worshipWordIcon"
  | "calendar"
  | "location"
  | "arrowLeftCircle"
  | "arrowRightCircle"
  | "play"
  | "wave"
  | "inbox"
  | "phone"
  | "email"
  | "navToggleIcon"
  | "audioWave"
  | "pause";
