export type IconNames =
  | "appLogo"
  | "mouseDown"
  | "arrowDownAnimation"
  | "cross"
  | "worshipWordIcon"
  | "calendar"
  | "location"
  | "arrowLeftCircle"
  | "arrowRightCircle"
  | "play"
  | "wave"
  | "inbox"
  | "phone"
  | "email";
